#!/bin/bash

spark-submit \
    --master k8s://https://bdcckkabanov-c38fb2c9.hcp.westeurope.azmk8s.io:443 \
    --deploy-mode cluster \
    --name spark-basics-hw \
    --conf spark.kubernetes.driver.secrets.sparkcreds=/etc/secrets \
    --conf spark.kubernetes.executor.secrets.sparkcreds=/etc/secrets \
    --conf spark.kubernetes.container.image=crkkabanovwesteurope.azurecr.io/spark/spark-azure-k8s:latest \
    --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
    --conf spark.kubernetes.container.image.pullPolicy=Always \
    local:///opt/spark/work-dir/spark-app/main/spark_main.py

